### ISSUE TITLE
cachedState is not defined

### ISSUE THREAD

**Issue by ChristianKlee** [benzman81/homebridge-http-webhooks#101]
I installed the plugin on my Synology Docker Homebridge and I had to change the chache directory to even start homebridge again to "cache_directory": "/homebridge/node-persist/storage".

Now I see my pushbuttons in Homekit and can use it but as soon as I try to active the button via url, homebridge crashes with this error:
`ReferenceError: cachedState is not defined
    at HttpWebHookPushButtonAccessory.changeFromServer (/usr/local/lib/node_modules/homebridge-http-webhooks/src/homekit/accessories/HttpWebHookPushButtonAccessory.js:34:17)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-http-webhooks/src/Server.js:123:38)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

I even set the cache directory the full permission and I installed the plugin globally. What else could be the solution?

**Comment by benzman81** [comment]
There was an issue as push button do not have a cached state. This is now fixed in 0.1.4.
