### ISSUE TITLE
Problem im Synology Docker

### ISSUE THREAD

**Issue by Pitti3301** [benzman81/homebridge-http-webhooks#138]
Hallo Markus,

erstmal vielen Dank für Deine Arbeit. Die Webhooks haben mir schon viel geholfen.
Vor ein paar Tagen habe ich Homebridge vom Raspberry auf Docker unter Synology NAS umgezogen. Leider klappt es mit den Webhooks seither nicht mehr. Laut Fehlermeldung irgendwelche Zugriffsrechte. Wo wäre das anzupassen?

Viele Grüße
Peter

Initializing HttpWebHooks platform...
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge-config-ui-x/.node-persist'
    at Object.mkdirSync (fs.js:1009:3)
    at sync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:72:13)
    at Function.sync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:78:24)
    at LocalStorage.parseStorageDirSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/node-persist.js:37:32)
    at new HttpWebHooksPlatform (/homebridge/node_modules/homebridge-http-webhooks/src/homekit/HttpWebHooksPlatform.js:27:16)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
Got SIGTERM, shutting down Homebridge...

**Comment by benzman81** [comment]
See https://github.com/benzman81/homebridge-http-webhooks#cache-directory-storage-cache_directory
