### ISSUE TITLE
 Error: EACCES: permission denied, mkdir '/persist' - previous solutions do not work

### ISSUE THREAD

**Issue by SuperJayRay** [benzman81/homebridge-http-webhooks#142]
I've tried everything. I do not uderstand how Homebridge's docker container is configured, as there is no documentation on it's directory or structure on the internet. I tried changing the cache directory to everything I can think of, including but not limited to /cache, /persist/http-requests, /homebridge/cache, /var/lib/homebridge/cache, etc. Of course, I tried to create these directories within Hyper-V first. One time the error message changed to something very different but still permissions related. I no longer have it though and can't replicate it. I edited /etc/passwd to give docker user 0 uid and 0 gid as well. Nothing has worked. Please help me fix this issue.

**Comment by benzman81** [comment]
Dont know your environment, but could you try a relative path like: `.homebridge-http-webhooks`?

**Comment by benzman81** [comment]
Ok, last idea is using `/homebridge/.homebridge-http-webhooks`. From the link you posted it seems that `/homebridge` seems to be a valid storage path.

**Comment by 391P** [comment]
Hello @benzman81.
I just wanted to switch my Homebridge to the Synology Docker. However, I get the same error message as published here in October. I could not see or read out a workaround! Here is the excerpt from the log. Can you help me please? 

[1/3/2022, 2:15:16 PM] [HttpWebHooks] Initializing HttpWebHooks platform...
[1/3/2022, 2:15:16 PM] Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge-config-ui-x/.node-persist'
    at Object.mkdirSync (node:fs:1334:3)
    at sync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:72:13)
    at Function.sync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:78:24)
    at LocalStorage.parseStorageDirSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/node-persist.js:37:32)
    at new HttpWebHooksPlatform (/homebridge/node_modules/homebridge-http-webhooks/src/homekit/HttpWebHooksPlatform.js:28:16)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)

**Comment by benzman81** [comment]
@391P no other information. Only the information that the configured folder must have permission.

**Comment by cypherpork** [comment]
@391P this is what worked for me:
Prep:
1. SSH to your Synology.
2. sudo docker container ls
3. Note your homebridge container ID, it will be something like 'bd37415ffa03'
4. sudo docker exec -it bd37415ffa03  /bin/sh
5. Now you are root inside your homebridge container. Next three steps are the actual workaround:
6. mkdir /run/s6/services/homebridge-config-ui-x/.node-persist
7. chgrp abc /run/s6/services/homebridge-config-ui-x/.node-persist
8. chmod 775 /run/s6/services/homebridge-config-ui-x/.node-persist

**Comment by nkpm** [comment]
I had the same issue with my homebridge docker setup. What solved the issue for me was setting cache_directory to /homebridge/webhookPersist/storage

The /run/s6/services/... path seems to be a false one the plugin retrieves while running in the container.

In my Dockerfile i could see that /homebridge was the right one...

**Comment by benzman81** [comment]
Thats why its configurable ;-)

**Comment by nkpm** [comment]
👍 and thx for the great plugin

**Comment by nkpm** [comment]
did you check the rights of the user you run homebridge with and the rights of the folder you pointed the plugin to?

**Comment by vifi42** [comment]
There seemed to have been a bigger problem with my homebridge. after uninstalling the plugin homebridge Itself starting throwing EISDIR Errors at me. After reflashing homebridge and redoing everything your plugin also worked fine. Seemed to have been a problem in my setup - whatever it was.
