### ISSUE TITLE
PARSE-ERROR

### ISSUE THREAD

**Issue by Vaifranz** [benzman81/homebridge-http-webhooks#164]
Hi, a problem emerged as a result of updating another plug-in (Yamaha AVR and uninstalled it) but I don't understand why, the problem is this:

```
    Error: [PARSE-ERROR] /homebridge/node-persist/storage/airplay does not look like a valid storage file!
    at LocalStorage.parseFileSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:647:19)
    at LocalStorage.parseStorageDirSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:596:26)
    at LocalStorage.initSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/homebridge/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/node-persist.js:37:32)
    at new HttpWebHooksPlatform (/homebridge/node_modules/homebridge-http-webhooks/src/homekit/HttpWebHooksPlatform.js:28:16)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:473:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:400:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:29)
```

and I have this setting:

```
            "webhook_port": "51828",
            "cache_directory": "/homebridge/node-persist/storage",
            "switches": [
```

Even if I create subfolders or place them in other folders it doesn't work. I use hombrigre with Docker in Synology NAS. Thanks in advance.

**Comment by benzman81** [comment]
Actually, the Readme explains it all ;-)

https://github.com/benzman81/homebridge-http-webhooks#cache-directory-storage-cache_directory

**Comment by Vaifranz** [comment]
I read it before writing, but it didn't solve my problem. To fix I had to delete the entire hombridge and reinstall it. I don't understand why. Thanks anyway.

**Comment by benzman81** [comment]
Maybe there have been some hidden files. Glad it works now.
