### ISSUE TITLE
TypeError: onSuccessCallback is not a function

### ISSUE THREAD

**Issue by Purikuri** [benzman81/homebridge-http-webhooks#98]
Hi 

Need some help understanding why I keep getting the error "TypeError: onSuccessCallback is not a function" when I turn a switch on.  I've installed the plugin through Homebridge "plugins", I've not edited anything any js files. 
This does not happen when I push a "Push Button". 

Any info would be gladly appreciated. 

Error message:
" TypeError: onSuccessCallback is not a function
    at Object.callHttpApi (/homebridge/node_modules/homebridge-http-webhooks/src/Util.js:41:5)
    at HttpWebHookSwitchAccessory.setState (/homebridge/node_modules/homebridge-http-webhooks/src/homekit/accessories/HttpWebHookSwitchAccessory.js:87:8)
    at On.emit (events.js:223:5)
    at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at On.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:651:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:10)
    at HAPServer.emit (events.js:223:5)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)"

**Comment by benzman81** [comment]
@Purikuri what does your config look like?

**Comment by benzman81** [comment]
@Purikuri got it, you have no URL set, correct? This is now fixed in 0.1.3.

**Comment by Purikuri** [comment]
@benzman81  it's correct I don't have any URL. 
thank you for the super fast reply
